2022-02-01 08:35:18,485 ERROR: Exception on /reset_password_request [GET] [in /Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/rossroberts/repositories/MediaTracker/app/routes.py", line 199, in reset_password_request
    return render_template('reset_password_request.html', title='Reset Password', form=form)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/rossroberts/repositories/MediaTracker/app/templates/reset_password_request.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/rossroberts/repositories/MediaTracker/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/rossroberts/repositories/MediaTracker/app/templates/reset_password_request.html", line 9, in block 'content'
    {{ form.email.size(64)}}
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/jinja2/utils.py", line 84, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'wtforms.fields.simple.StringField object' has no attribute 'size'
2022-02-01 08:36:38,999 INFO: MediaTracker Startup [in /Users/rossroberts/repositories/MediaTracker/app/__init__.py:47]
2022-02-01 08:36:48,549 ERROR: Exception on /reset_password_request [POST] [in /Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/rossroberts/repositories/MediaTracker/app/routes.py", line 194, in reset_password_request
    user.User.query.filter_by(email=form.email.data).first()
AttributeError: 'function' object has no attribute 'User'
2022-02-01 08:38:39,292 INFO: MediaTracker Startup [in /Users/rossroberts/repositories/MediaTracker/app/__init__.py:47]
2022-02-01 08:38:48,476 ERROR: Exception on /reset_password_request [POST] [in /Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/rossroberts/repositories/MediaTracker/app/routes.py", line 196, in reset_password_request
    send_password_reset_email(user)
  File "/Users/rossroberts/repositories/MediaTracker/app/email.py", line 12, in send_password_reset_email
    token = user.get_password_reset_token()
AttributeError: 'User' object has no attribute 'get_password_reset_token'
2022-02-01 08:40:00,163 INFO: MediaTracker Startup [in /Users/rossroberts/repositories/MediaTracker/app/__init__.py:47]
2022-02-01 08:40:12,148 ERROR: Exception on /reset_password_request [POST] [in /Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/rossroberts/repositories/MediaTracker/app/routes.py", line 196, in reset_password_request
    send_password_reset_email(user)
  File "/Users/rossroberts/repositories/MediaTracker/app/email.py", line 12, in send_password_reset_email
    token = user.get_password_reset_token()
  File "/Users/rossroberts/repositories/MediaTracker/app/models.py", line 51, in get_password_reset_token
    return jwt.encode(
AttributeError: module 'jwt' has no attribute 'encode'
2022-02-01 08:42:20,248 INFO: MediaTracker Startup [in /Users/rossroberts/repositories/MediaTracker/app/__init__.py:47]
2022-02-01 08:42:28,260 ERROR: Exception on /reset_password_request [POST] [in /Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rossroberts/repositories/MediaTracker/env/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/rossroberts/repositories/MediaTracker/app/routes.py", line 196, in reset_password_request
    send_password_reset_email(user)
  File "/Users/rossroberts/repositories/MediaTracker/app/email.py", line 13, in send_password_reset_email
    send_email('[MediaTracker] Reset Your Password',
TypeError: send_email() got an unexpected keyword argument 'html_body'
2022-02-01 08:43:07,694 INFO: MediaTracker Startup [in /Users/rossroberts/repositories/MediaTracker/app/__init__.py:47]
